// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class StudentResource_retrieveAllStudents_874a3b8f8a_Test {

    @InjectMocks
    StudentResource studentResource;

    @Mock
    StudentRepository studentRepository;

    @Test
    public void testRetrieveAllStudents_returnAllStudents() {
        // TODO: Replace with actual Student objects
        Student student1 = new Student();
        Student student2 = new Student();
        List<Student> expectedStudents = Arrays.asList(student1, student2);
        when(studentRepository.findAll()).thenReturn(expectedStudents);

        List<Student> actualStudents = studentResource.retrieveAllStudents();

        assertEquals(expectedStudents, actualStudents);
    }

    @Test
    public void testRetrieveAllStudents_returnEmptyList() {
        List<Student> expectedStudents = Arrays.asList();
        when(studentRepository.findAll()).thenReturn(expectedStudents);

        List<Student> actualStudents = studentResource.retrieveAllStudents();

        assertEquals(expectedStudents, actualStudents);
    }
}
