// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class StudentResource_retrieveStudent_17d4a4d79b_Test {

    @InjectMocks
    private StudentResource studentResource;

    @Mock
    private StudentRepository studentRepository;

    @Test
    public void testRetrieveStudent_Success() {
        Student student = new Student(1, "Test Student", "Test Course");
        when(studentRepository.findById(1L)).thenReturn(Optional.of(student));

        Student result = studentResource.retrieveStudent(1L);

        assertEquals(student, result, "Expected and actual students should match");
    }

    @Test
    public void testRetrieveStudent_NotFound() {
        when(studentRepository.findById(1L)).thenReturn(Optional.empty());

        assertThrows(StudentNotFoundException.class, () -> {
            studentResource.retrieveStudent(1L);
        }, "Expected StudentNotFoundException to be thrown");
    }
}
