// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Student_getPassportNumber_e9f9565fde_Test {
    
    @Mock
    private Student student;

    @InjectMocks
    private StudentService studentService;

    @Test
    public void testGetPassportNumber() {
        String expectedPassportNumber = "123456789";
        when(student.getPassportNumber()).thenReturn(expectedPassportNumber);
        String actualPassportNumber = studentService.getPassportNumber(student);
        assertEquals(expectedPassportNumber, actualPassportNumber);
    }

    @Test
    public void testGetPassportNumber_Null() {
        when(student.getPassportNumber()).thenReturn(null);
        String actualPassportNumber = studentService.getPassportNumber(student);
        assertEquals(null, actualPassportNumber);
    }
}
