// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Student_setId_04a8e16b7c_Test {

    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
    }

    @Test
    public void testSetId_PositiveNumber() {
        Long id = 123L;
        student.setId(id);
        assertEquals(id, student.getId());
    }

    @Test
    public void testSetId_Zero() {
        Long id = 0L;
        student.setId(id);
        assertEquals(id, student.getId());
    }

    @Test
    public void testSetId_Null() {
        Long id = null;
        student.setId(id);
        assertEquals(id, student.getId());
    }
}
