// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.http.ResponseEntity;
import org.springframework.boot.test.context.SpringBootTest;
import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;

import java.util.Optional;

@SpringBootTest
public class StudentResource_updateStudent_d36c73ffe2_Test {

    @InjectMocks
    private StudentResource studentResource;

    @Mock
    private StudentRepository studentRepository;

    @Test
    public void testUpdateStudent_Success() {
        Student student = new Student("Test", "Test");
        student.setId(1L);
        when(studentRepository.findById(anyLong())).thenReturn(Optional.of(student));
        when(studentRepository.save(any(Student.class))).thenReturn(student);

        ResponseEntity<Object> responseEntity = studentResource.updateStudent(student, 1L);

        assertEquals(204, responseEntity.getStatusCodeValue());
    }

    @Test
    public void testUpdateStudent_NotFound() {
        Student student = new Student("Test", "Test");
        student.setId(1L);
        when(studentRepository.findById(anyLong())).thenReturn(Optional.empty());

        ResponseEntity<Object> responseEntity = studentResource.updateStudent(student, 1L);

        assertEquals(404, responseEntity.getStatusCodeValue());
    }
}
