// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Student_getName_8400ac6fb7_Test {

    @Test
    public void testNameGetterWithActualName() {
        // Given
        Student student = Mockito.mock(Student.class);
        Mockito.when(student.getName()).thenReturn("John Doe");

        // When
        String actualName = student.getName();

        // Then
        Assertions.assertEquals("John Doe", actualName);
    }

    @Test
    public void testNameGetterWithNoName() {
        // Given
        Student student = Mockito.mock(Student.class);
        Mockito.when(student.getName()).thenReturn("");

        // When
        String actualName = student.getName();

        // Then
        Assertions.assertEquals("", actualName);
    }
}
