// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;

import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class StudentResource_deleteStudent_0348006656_Test {

    @InjectMocks
    StudentResource studentResource;

    @Mock
    StudentRepository studentRepository;

    @Test
    public void testDeleteStudentSuccess() {
        long id = 1;
        doNothing().when(studentRepository).deleteById(id);

        studentResource.deleteStudent(id);

        verify(studentRepository, times(1)).deleteById(id);
    }

    @Test
    public void testDeleteStudentFailure() {
        long id = 1;
        doThrow(new RuntimeException()).when(studentRepository).deleteById(id);

        try {
            studentResource.deleteStudent(id);
        } catch (RuntimeException e) {
            // TODO: Handle exception
        }

        verify(studentRepository, times(1)).deleteById(id);
    }
}
