// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Student_Student_6583406a35_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student(1L, "John Doe", "A1234567");
    }

    @Test
    public void testStudentId() {
        Long expectedId = 1L;
        assertEquals(expectedId, student.getId());
    }

    @Test
    public void testStudentName() {
        String expectedName = "John Doe";
        assertEquals(expectedName, student.getName());
    }
    
    @Test
    public void testStudentPassportNumber() {
        String expectedPassportNumber = "A1234567";
        assertEquals(expectedPassportNumber, student.getPassportNumber());
    }
}
