// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Student_setName_5d23a892d9_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testNameSetCorrectly() {
        String expectedName = "John Doe";
        student.setName(expectedName);
        Assertions.assertEquals(expectedName, student.getName());
    }

    @Test
    public void testSetNameWithEmptyString() {
        String expectedName = "";
        student.setName(expectedName);
        Assertions.assertEquals(expectedName, student.getName());
    }
}
