// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_Student_4f0c49de05_Test {

    @Test
    public void testStudentCreation() {
        Student student = new Student();
        Assertions.assertNotNull(student, "Student object should not be null");
    }

    @Test
    public void testStudentId() {
        Student student = new Student();
        Assertions.assertNull(student.getId(), "Newly created student id should be null");
    }
}
