// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Student_setPassportNumber_27b9a7834a_Test {

    @Mock
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetPassportNumber() {
        String passportNumber = "123456789";
        student.setPassportNumber(passportNumber);
        Assertions.assertEquals(passportNumber, student.getPassportNumber(), "Passport numbers should be equal");
    }

    @Test
    public void testSetPassportNumberWithNull() {
        String passportNumber = null;
        student.setPassportNumber(passportNumber);
        Assertions.assertNull(student.getPassportNumber(), "Passport number should be null");
    }
}
