// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.Assert.assertEquals;

public class Student_setPassportNumber_27b9a7834a_Test {

    @InjectMocks
    private Student student;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetPassportNumber() {
        String passportNumber = "A1234567";
        student.setPassportNumber(passportNumber);
        assertEquals("Passport number is not set correctly", passportNumber, student.getPassportNumber());
    }

    @Test
    public void testSetPassportNumberWithNull() {
        student.setPassportNumber(null);
        assertEquals("Passport number should be null", null, student.getPassportNumber());
    }
}
