// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setId_04a8e16b7c_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetId_PositiveNumber() {
        Long id = 1L;
        student.setId(id);
        assertEquals(id, student.getId(), "The ID should match the value set");
    }

    @Test
    public void testSetId_NegativeNumber() {
        Long id = -1L;
        student.setId(id);
        assertEquals(id, student.getId(), "The ID should match the value set, even if it's negative");
    }

    @Test
    public void testSetId_Null() {
        student.setId(null);
        assertEquals(null, student.getId(), "The ID should match the value set, even if it's null");
    }
}
