// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
public class Student_Student_4f0c49de05_Test {

    @MockBean
    private StudentRepository studentRepository;

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testStudentConstructor() {
        assertNotNull(student);
    }

    @Test
    public void testStudentConstructorWithMock() {
        Student mockStudent = Mockito.mock(Student.class);
        Mockito.when(studentRepository.save(mockStudent)).thenReturn(mockStudent);
        Student savedStudent = studentRepository.save(mockStudent);
        assertEquals(mockStudent, savedStudent);
    }
}
