// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

@Entity
public class Student_Student_6583406a35_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testStudentConstructor() {
        Long id = 1L;
        String name = "John Doe";
        String passportNumber = "123456";

        student = new Student(id, name, passportNumber);

        assertEquals(id, student.getId());
        assertEquals(name, student.getName());
        assertEquals(passportNumber, student.getPassportNumber());
    }

    @Test
    public void testStudentConstructor_EmptyValues() {
        Long id = null;
        String name = "";
        String passportNumber = "";

        student = new Student(id, name, passportNumber);

        assertEquals(id, student.getId());
        assertEquals(name, student.getName());
        assertEquals(passportNumber, student.getPassportNumber());
    }
}
