// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setId_04a8e16b7c_Test {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetId_positive() {
        Long expectedId = 100L;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId());
    }

    @Test
    public void testSetId_null() {
        student.setId(null);
        assertEquals(null, student.getId());
    }
}
