// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Student_getPassportNumber_e9f9565fde_Test {

    @Mock
    private Student student;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPassportNumber() {
        String expectedPassportNumber = "123456789";
        Mockito.when(student.getPassportNumber()).thenReturn(expectedPassportNumber);
        String actualPassportNumber = student.getPassportNumber();
        Assertions.assertEquals(expectedPassportNumber, actualPassportNumber);
    }

    @Test
    public void testGetPassportNumberWhenPassportNumberIsNull() {
        Mockito.when(student.getPassportNumber()).thenReturn(null);
        String actualPassportNumber = student.getPassportNumber();
        Assertions.assertNull(actualPassportNumber);
    }
}
