// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_getId_ba349b1eff_Test {

    @Test
    public void testGetId() {
        Student student = new Student();
        student.setId(123L);
        Long expectedId = 123L;
        Long actualId = student.getId();
        assertEquals(expectedId, actualId);
    }

    @Test
    public void testGetIdWithNoIdSet() {
        Student student = new Student();
        Long expectedId = null;
        Long actualId = student.getId();
        assertEquals(expectedId, actualId);
    }
}
