// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
public class StudentResource_retrieveAllStudents_874a3b8f8a_Test {

    @InjectMocks
    private StudentResource studentResource;

    @Mock
    private StudentRepository studentRepository;

    @Test
    public void testRetrieveAllStudents() {
        Student student1 = new Student("John", "Maths");
        Student student2 = new Student("Jane", "Physics");
        List<Student> expectedStudents = Arrays.asList(student1, student2);

        when(studentRepository.findAll()).thenReturn(expectedStudents);

        List<Student> actualStudents = studentResource.retrieveAllStudents();

        assertEquals(expectedStudents, actualStudents);
    }

    @Test
    public void testRetrieveAllStudents_emptyList() {
        List<Student> expectedStudents = Arrays.asList();

        when(studentRepository.findAll()).thenReturn(expectedStudents);

        List<Student> actualStudents = studentResource.retrieveAllStudents();

        assertEquals(expectedStudents, actualStudents);
    }
}
