// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setPassportNumber_27b9a7834a_Test {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetPassportNumber() {
        String passportNumber = "123456789";
        student.setPassportNumber(passportNumber);
        assertEquals(passportNumber, student.getPassportNumber(), "Passport number should be set correctly");
    }

    @Test
    public void testSetPassportNumberWithEmptyString() {
        String passportNumber = "";
        student.setPassportNumber(passportNumber);
        assertEquals(passportNumber, student.getPassportNumber(), "Passport number should be set correctly even if it's an empty string");
    }
}
