// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

public class Student_Student_6583406a35_Test {

    @Test
    public void testStudentConstructor() {
        Student student = new Student(1L, "John Doe", "AB123456");
        Assertions.assertEquals(1L, student.getId());
        Assertions.assertEquals("John Doe", student.getName());
        Assertions.assertEquals("AB123456", student.getPassportNumber());
    }

    @Test
    public void testStudentConstructorWithNullValues() {
        Student student = new Student(null, null, null);
        Assertions.assertNull(student.getId());
        Assertions.assertNull(student.getName());
        Assertions.assertNull(student.getPassportNumber());
    }
}
