// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_setName_5d23a892d9_Test {

    @Test
    public void testSetNameSuccess() {
        Student student = new Student();
        String expectedName = "John Doe";
        student.setName(expectedName);
        assertEquals(expectedName, student.getName());
    }

    @Test
    public void testSetNameNull() {
        Student student = new Student();
        String expectedName = null;
        student.setName(expectedName);
        assertEquals(expectedName, student.getName());
    }
}
