// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class StudentNotFoundException_StudentNotFoundException_339848f0dc_Test {

    private StudentNotFoundException exception;

    @BeforeEach
    public void setUp() {
        exception = new StudentNotFoundException("Test exception");
    }

    @Test
    public void testExceptionMessage() {
        assertEquals("Test exception", exception.getMessage());
    }

    @Test
    public void testExceptionThrowing() {
        assertThrows(StudentNotFoundException.class, () -> {
            throw new StudentNotFoundException("Test exception");
        });
    }
}
