// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class Student_setName_5d23a892d9_Test {

    @Test
    public void testSetName() {
        Student student = new Student();
        String expectedName = "John Doe";
        student.setName(expectedName);
        Assertions.assertEquals(expectedName, student.getName());
    }

    @Test
    public void testSetNameNull() {
        Student student = new Student();
        student.setName(null);
        Assertions.assertNull(student.getName());
    }

    @Test
    public void testSetNameEmpty() {
        Student student = new Student();
        student.setName("");
        Assertions.assertEquals("", student.getName());
    }
}
