// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Student_getName_8400ac6fb7_Test {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetName_WithValidName() {
        String expectedName = "John Doe";
        student.setName(expectedName);
        String actualName = student.getName();
        Assertions.assertEquals(expectedName, actualName, "The name should be " + expectedName);
    }

    @Test
    public void testGetName_WithNullName() {
        student.setName(null);
        String actualName = student.getName();
        Assertions.assertNull(actualName, "The name should be null");
    }

}
