// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Student_getName_8400ac6fb7_Test {

    private Student student;

    @BeforeEach
    void setUp() {
        student = new Student();
    }

    @Test
    void testGetName() {
        String expectedName = "John Doe";
        student.setName(expectedName);
        String actualName = student.getName();
        assertEquals(expectedName, actualName, "The student's name should be John Doe");
    }

    @Test
    void testGetNameWhenNameNotSet() {
        String actualName = student.getName();
        assertNull(actualName, "The student's name should be null as it has not been set yet");
    }
}
