// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Student_getId_ba349b1eff_Test {

    @Test
    public void testGetIdSuccess() {
        Student student = Mockito.mock(Student.class);
        Mockito.when(student.getId()).thenReturn(1L);
        Assertions.assertEquals(1L, student.getId());
    }

    @Test
    public void testGetIdFailure() {
        Student student = Mockito.mock(Student.class);
        Mockito.when(student.getId()).thenReturn(null);
        Assertions.assertNull(student.getId());
    }
}
