// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

@Entity
public class Student_getId_ba349b1eff_Test {

    private Student student;

    @Id
    @GeneratedValue
    private Long id;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testGetIdSuccess() {
        student.setId(123L);
        Long expectedId = 123L;
        Assertions.assertEquals(expectedId, student.getId());
    }

    @Test
    public void testGetIdFailure() {
        Long expectedId = 123L;
        Assertions.assertNotEquals(expectedId, student.getId());
    }
}
