// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import org.springframework.boot.test.context.SpringBootTest;

import java.util.NoSuchElementException;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class StudentResource_deleteStudent_0348006656_Test {

    @InjectMocks
    StudentResource studentResource;

    @Mock
    StudentRepository studentRepository;

    @Test
    public void testDeleteStudentSuccess() {
        long id = 1L;
        doNothing().when(studentRepository).deleteById(id);
        studentResource.deleteStudent(id);
        verify(studentRepository, times(1)).deleteById(id);
    }

    @Test
    public void testDeleteStudentFailure() {
        long id = 1L;
        when(studentRepository.deleteById(id)).thenThrow(new NoSuchElementException());
        assertThrows(NoSuchElementException.class, () -> studentResource.deleteStudent(id));
        verify(studentRepository, times(1)).deleteById(id);
    }
}
