// Test generated by RoostGPT for test RestBasicService using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;

public class Student_Student_4f0c49de05_Test {

    @Mock
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
        student = new Student();
    }

    @Test
    public void testStudentObjectCreation() {
        assertNotNull(student, "Student object should not be null after initialization");
    }

    @Test
    public void testStudentObjectProperties() {
        student.setId(1L);
        student.setName("Test Student");
        student.setPassportNumber("E1234567");

        assertEquals(1L, student.getId(), "Student ID should be 1L");
        assertEquals("Test Student", student.getName(), "Student name should be 'Test Student'");
        assertEquals("E1234567", student.getPassportNumber(), "Student passport number should be 'E1234567'");
    }
}
